### ISSUE TITLE
[BUG] - Pipeline stack Error

### ISSUE THREAD

**Issue by allamand** [aws-quickstart/ssp-amazon-eks#152]
Trying to follow the pipeline stack from default but I had several errors : 

1. npm ci error
  ```
  npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
  ```
  
  I fixed this by commiting the `package-lock.json` file

2. error on cdk synth

  ```
  [Container] 2021/08/06 14:05:29 Running command npx cdk synth
  current credentials could not be used to assume 'arn:aws:iam::xxxxxx:role/cdk-hnb659fds-lookup-role-xxxxxx-eu-west-1', but are for the right account. Proceeding anyway.
  [Error at /blueprint-construct-dev] You are not authorized to perform this operation.
  Found errors
  ```
  
  I fied this by commiting my cdk.context.json file

3. the Assets jobs failed

  with 1. and 2. fix, the build was ok, but it fails now at the Assets stage:
  
  ![image](https://user-images.githubusercontent.com/8956643/128528201-dd9a6051-c423-4dbe-80bb-b64e29ea06c6.png)

  the error message is
  ```
  Error: Cannot read asset manifest at 'assembly-pipeline-blueprint-dev/pipelineblueprintdeveks1AFA1B3B.assets.json': ENOENT: no such file or directory, stat 'assembly-pipeline-blueprint-dev/pipelineblueprintdeveks1AFA1B3B.assets.json'
  ```

I'm not sur how to recover from the last one, i was testing in eu-west-1

**Comment by kcoleman731** [comment]
Thanks for reporting this @allamand. Let us look into this and get back to you.

**Comment by shapirov103** [comment]
This is fixed by https://github.com/aws-quickstart/ssp-amazon-eks/pull/184 and https://github.com/aws-samples/ssp-eks-patterns/pull/2. 

You will need to pull the latest from https://github.com/aws-samples/ssp-eks-patterns and follow the example in the `lib/pipeline-stack/index.ts`.

At present, it requires having AWS credentials configured on AWS CLI (e.g. `aws configure`). 
<img width="1249" alt="Screen Shot 2021-08-24 at 3 56 38 PM" src="https://user-images.githubusercontent.com/60622975/130682185-565d6398-dd18-45a8-a452-68b9a85a8bee.png">

**Comment by shapirov103** [comment]
I will keep it open for a bit in case you have any feedback.
