### ISSUE TITLE
[BUG] - ExternalDNS + Nginx deployment order

### ISSUE THREAD

**Issue by kcoleman731** [aws-quickstart/ssp-amazon-eks#183]
If Nginx is deployed after ExternalDNS, the NLB does not get deployed. 

If ArgoCD is deployed before either, the ingress do not create the relevant records in Route53.

**Comment by shapirov103** [comment]
1. 'Nginx is deployed after ExternalDNS` - this has no impact on NLB. I assume you meant Nginx deployed before AWS Load Balancer controller. 
2. ArgoCD app creation is a post deployment hook and workloads are pulled in asynchronously through GitOps. I assume because NLB was not provisioned in the first place, nothing will work.
